name: Run script

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow

jobs:
  run_script:
    runs-on: ubuntu-latest  # Change this to the desired operating system

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
   
      - name: Install dependencies
        run: pip install boto3  # Install any required dependencies
 
      - name: Install dependenciess
        run: pip install requests

      - name: Run script
        run: python main.py  # Replace 'script.py' with the actual filename
